Vonage/vonage-dotnet-sdk

- CHANGELOG.md
- Nexmo.Api.Test.Integration/Nexmo.Api.Test.Integration.csproj
- Nexmo.Api.Test.Integration/ThrottleTest.cs
- Nexmo.Api.Test.Unit/Nexmo.Api.Test.Unit.csproj
- Nexmo.Api/Configuration.cs
- Nexmo.Api/Nexmo.Api.xproj
- Nexmo.Api/Request/ThrottlingMessageHandler.cs
- Nexmo.Api/Request/TimeSpanSemaphore.cs
- README.md
> Support optional throttling

- README.md
Changed Call API to Voice API and other stylistic improvements
> Style improvements

- Nexmo.Api/Request/Credentials.cs
hey @smithrobs , seems like users are expecting to init api auth details via constructors. Let me know if you have any objections to this . thanks
> Adding constructors for basic and full auth

- CHANGELOG.md
- Nexmo.Api/Client/Client.cs
- Nexmo.Api/Client/Redact.cs
- Nexmo.Api/Request/ApiRequest.cs
- Nexmo.api/Redact.cs
- README.md
* Added Redact API implementation
* Updated README 
* Updated CHANGELOG
> Redact implementation

- README.md
Added a dot to the end of the License-section and removed an unused Create Account-link.
> Updated readme small text fixes

- Nexmo.Api/Nexmo.Api.nuspec
- Nexmo.Api/Properties/AssemblyInfo.cs
Apparently the nuspec has not been kept in sync with what is in nuget - Adding all the dependencies reflected in 4.0.0 nuget so that everything is harmonized
> Harmonizing dependencies 

- Nexmo.Api.Test.Unit/ApplicationV2Test.cs
- Nexmo.Api.Test.Unit/JwtTest.cs
- Nexmo.Api.Test.Unit/Nexmo.Api.Test.Unit.csproj
- Nexmo.Api.Test.Unit/NumberTest.cs
- Nexmo.Api/ApplicationV2.cs
- Nexmo.Api/Nexmo.Api.nuspec
- Nexmo.Api/Request/ApiRequest.cs
- Nexmo.Api/Request/VersionedApiRequest.cs
- Nexmo.Api/Voice/Call.cs
Fixing Unit Test cases,
Fixed several NRE issues one where you'd get a NRE for a couple of API calls if you were configuring ,
Fixed Microsoft.Extensions.Configuration.Abstraction dependency issue,
Made the Application List function go through the same set of common https request helper functions that everything else uses (this was preventing the DI in the unit test from working) - needed to add flag to choose auth type in function.
> Fixing Unit tests, fixing Application flow, fixing possible NRE

- Nexmo.Api/Nexmo.Api.nuspec
- Nexmo.Api/Voice/Nccos/NotifyAction.cs
- Nexmo.Api/voice/Nccos/NccoConverter.cs
Bug in NCCO Converter was causing weird output for objects / arrays - swapping out default serializer for objects
> Fixing Ncco serialization bug

- Nexmo.Api/Client/Number.cs
- Nexmo.Api/Jwt.cs
- Nexmo.Api/Nexmo.Api.nuspec
- Nexmo.Api/Number.cs
- Nexmo.Api/Properties/AssemblyInfo.cs
Making JWT Generation public, adding list own numbers API to Number client. Revving spec to 4.3.0
> Feature/add list own numbers make JWT generator public

- Nexmo.Api.Test.Integration/CallTest.cs
- Nexmo.Api.Test.Unit/StreamActionTest.cs
- Nexmo.Api/Voice/Nccos/StreamAction.cs
> Serialize streamUrl as array per docs to avoid bad request

- Nexmo.Api.Test.Unit/MultiInputTests.cs
- Nexmo.Api.Test.Unit/SpeechAsrTests.cs
- Nexmo.Api/Nexmo.Api.csproj
- Nexmo.Api/Nexmo.Api.nuspec
- Nexmo.Api/Properties/AssemblyInfo.cs
- Nexmo.Api/Voice/EventWebhooks/DtmfResult.cs
- Nexmo.Api/Voice/EventWebhooks/EventBase.cs
- Nexmo.Api/Voice/EventWebhooks/Input.cs
- Nexmo.Api/Voice/EventWebhooks/MultiInput.cs
- Nexmo.Api/Voice/EventWebhooks/SpeechRecognitionResult.cs
- Nexmo.Api/Voice/EventWebhooks/SpeechResult.cs
- Nexmo.Api/Voice/Nccos/DtmfSettings.cs
- Nexmo.Api/Voice/Nccos/InputAction.cs
- Nexmo.Api/Voice/Nccos/MultiInputAction.cs
- Nexmo.Api/Voice/Nccos/SpeechSettings.cs
Adding the new ASR webhook and input items to the SDK
Incrementing version to 4.4.0
> adding ASR webhook and input items

- Nexmo.Api/Nexmo.Api.csproj
- Nexmo.Api/Nexmo.Api.nuspec
- Nexmo.Api/Properties/AssemblyInfo.cs
- Nexmo.Api/Request/VersionedApiRequest.cs
Encodings for json payloads should be utf8 rather than ASCII - updating the encoding to utf8
> changing payload encoding to utf8

- README.md
- Vonage/Vonage.nuspec
Minor fix to the licence fied in the nuspec. Adding API compatibility list to README.
> adding compatibility list, fixing nuspec

- Vonage/LegacyNexmoLibrary/Messaging/InboundSms.cs
query null check issue to InboundSms.cs
#hacktoberfest
> query null check issue

- Vonage/LegacyNexmoLibrary/Verify/Psd2Request.cs
- Vonage/LegacyNexmoLibrary/Verify/VerifyRequest.cs
- Vonage/Verify/Psd2Request.cs
- Vonage/Verify/VerifyRequest.cs
> Correcting enumeration of workflow

- README.md
Fixes #224 
fixed spelling of word 'globally'.
> Typo fix - Update README.md

- README.md
Quick FAQ Addition for the async pattern - will hopefully be rendered irrelevant by #223  soon
> Adding FAQ Section - one question for async at the moment.

- Vonage.Test.Unit/NccoTests.cs
- Vonage.Test.Unit/VoiceClientTests.cs
- Vonage/Voice/Nccos/TalkAction.cs
- Vonage/Voice/TalkCommand.cs
- Vonage/Vonage.csproj
- Vonage/Vonage.nuspec
Adding language and style fields to Talk NCCO and Talk Command, also dropping some unnecessary usings.
> Adding Language and style, marking VoiceName as obsolete

- Vonage.Test.Unit/MessagingTests.cs
- Vonage/Messaging/ISmsClient.cs
- Vonage/Messaging/SmsClient.cs
In reference to #222 
Simplifies the way an sms can be sent.
> Enhancements to the ISmsClient

- Vonage/NumberInsights/AdvancedInsightsAsyncResponse.cs
- Vonage/NumberInsights/AdvancedInsightsResponse.cs
- Vonage/NumberInsights/NumberInsightResponseBase.cs
- Vonage/NumberInsights/RealTimeData.cs
- Vonage/Properties/AssemblyInfo.cs
- Vonage/Vonage.csproj
- Changing version numbers ready for release
- Adding real-time data property to Advance Number Insights response
> Preparing for next release and real time data

- Vonage.Test.Unit/Data/MessagesTests/SendMessengerAudioAsyncReturnsOk-request.json
- Vonage.Test.Unit/Data/MessagesTests/SendMessengerAudioAsyncReturnsOk-response.json
- Vonage.Test.Unit/Data/MessagesTests/SendMessengerFileAsyncReturnsOk-request.json
- Vonage.Test.Unit/Data/MessagesTests/SendMessengerFileAsyncReturnsOk-response.json
- Vonage.Test.Unit/Data/MessagesTests/SendMessengerImageAsyncReturnsOk-request.json
- Vonage.Test.Unit/Data/MessagesTests/SendMessengerImageAsyncReturnsOk-response.json
- Vonage.Test.Unit/Data/MessagesTests/SendMessengerTextAsyncReturnsOk-request.json
- Vonage.Test.Unit/Data/MessagesTests/SendMessengerTextAsyncReturnsOk-response.json
- Vonage.Test.Unit/Data/MessagesTests/SendMessengerVideoAsyncReturnsOk-request.json
- Vonage.Test.Unit/Data/MessagesTests/SendMessengerVideoAsyncReturnsOk-response.json
- Vonage.Test.Unit/Data/MessagesTests/SendMmsVideoAsyncReturnsOk-request.json
- Vonage.Test.Unit/Data/MessagesTests/SendViberImageAsyncReturnsOk-request.json
- Vonage.Test.Unit/Data/MessagesTests/SendViberImageAsyncReturnsOk-response.json
- Vonage.Test.Unit/Data/MessagesTests/SendViberTextAsyncReturnsOk-request.json
- Vonage.Test.Unit/Data/MessagesTests/SendViberTextAsyncReturnsOk-response.json
- Vonage.Test.Unit/MessagesTests.cs
- Vonage.Test.Unit/Vonage.Test.Unit.csproj
- Vonage/Messages/Messenger/MessengerAudioRequest.cs
- Vonage/Messages/Messenger/MessengerFileRequest.cs
- Vonage/Messages/Messenger/MessengerImageRequest.cs
- Vonage/Messages/Messenger/MessengerMessageCategory.cs
- Vonage/Messages/Messenger/MessengerRequestData.cs
- Vonage/Messages/Messenger/MessengerTagType.cs
- Vonage/Messages/Messenger/MessengerTextRequest.cs
- Vonage/Messages/Messenger/MessengerVideoRequest.cs
- Vonage/Messages/Viber/ViberImageRequest.cs
- Vonage/Messages/Viber/ViberMessageCategory.cs
- Vonage/Messages/Viber/ViberRequestData.cs
- Vonage/Messages/Viber/ViberTextRequest.cs
This change adds in functionality for sending Messenger and Viber messages through the Messages API
> Messenger and Viber

- Vonage.Test.Unit/NccoTests.cs
- Vonage.Test.Unit/NumberInsightsTests.cs
- Vonage/NumberInsights/AdvancedInsightsAsynchronousResponse.cs
- Vonage/NumberInsights/INumberInsightClient.cs
- Vonage/NumberInsights/NumberInsightClient.cs
- Vonage/Serialization/VonageSerialization.cs
- Vonage/Voice/Nccos/Ncco.cs
- Vonage/Vonage.csproj
Making Serialisation Settings public
Reinstating ToString in Ncco.cs
Removing `VersionPrefix` from project file as to not confuse
> Small fixes for v6

- Vonage/Accounts/AccountClient.cs
- Vonage/Accounts/CreateSubAccountRequest.cs
- Vonage/Accounts/IAccountClient.cs
- Vonage/Accounts/SubAccount.cs
- Vonage/Numbers/INumbersClient.cs
- Vonage/Numbers/NumberTransferRequest.cs
- Vonage/Numbers/NumberTransferResponse.cs
- Vonage/Numbers/NumbersClient.cs
- Vonage/Vonage.csproj
- Create a subaccount
- Retrieve a subaccount
- Transfer number between subaccounts
> Simple subaccount support

- Vonage.Common.Test/UseCaseHelper.cs
- Vonage.Server.Test/Video/Archives/AddStream/AddStreamTest.cs
- Vonage.Server.Test/Video/Archives/ChangeLayout/ChangeLayoutTest.cs
- Vonage.Server.Test/Video/Archives/CreateArchive/CreateArchiveTest.cs
- Vonage.Server.Test/Video/Archives/DeleteArchive/DeleteArchiveTest.cs
- Vonage.Server.Test/Video/Archives/GetArchive/GetArchiveTest.cs
- Vonage.Server.Test/Video/Archives/GetArchives/GetArchivesTest.cs
- Vonage.Server.Test/Video/Archives/RemoveStream/RemoveStreamTest.cs
- Vonage.Server.Test/Video/Archives/StopArchive/StopArchiveTest.cs
- Vonage.Server.Test/Video/Moderation/DisconnectConnection/DisconnectConnectionTest.cs
- Vonage.Server.Test/Video/Moderation/MuteStream/MuteStreamTest.cs
- Vonage.Server.Test/Video/Moderation/MuteStreams/MuteStreamsTest.cs
- Vonage.Server.Test/Video/Sessions/ChangeStreamLayout/ChangeStreamLayoutTest.cs
- Vonage.Server.Test/Video/Sessions/CreateSession/CreateSessionTest.cs
- Vonage.Server.Test/Video/Sessions/GetStream/GetStreamTest.cs
- Vonage.Server.Test/Video/Sessions/GetStreams/GetStreamsTest.cs
- Vonage.Server.Test/Video/Signaling/SendSignal/SendSignalTest.cs
- Vonage.Server.Test/Video/Signaling/SendSignals/SendSignalsTest.cs
- Vonage.Test.Unit/Meetings/GetAvailableRooms/GetAvailableRoomsTest.cs
- Vonage.Test.Unit/Meetings/GetRoom/GetRoomTest.cs
- Vonage.Test.Unit/Vonage.Test.Unit.csproj
- Reduce duplication on PBT
- Reduce duplication in verifying responses
- Remove netcoreapp3.1 from Vonage.Test.Unit
> Refactoring on *.Test

- .github/workflows/multiframework-build.yml
- .github/workflows/net6-build.yml
- Vonage.Common.Test/Vonage.Common.Test.csproj
- Vonage.Server.Test/Vonage.Server.Test.csproj
- Vonage.Test.Unit/Vonage.Test.Unit.csproj
- Vonage.sln
Focus main build on .net6.0 to improve feedback loop
Add separate pipeline to test all frameworks on push
> Pipeline updates

- .github/workflows/multiframework-build.yml
- .github/workflows/net6-build.yml
- README.md
- Vonage.Server.Test/Authentication/VideoTokenGeneratorTest.cs
- Vonage.Test.Unit/ApplicationTests.cs
- Vonage.Test.Unit/Data/ApplicationTests/CreateApplication-request.json
- Vonage.Test.Unit/Data/ApplicationTests/CreateApplication-response.json
- Vonage.Test.Unit/JwtTest.cs
- Vonage.Test.Unit/TestBase.cs
- Replace RSA Private Keys with environment variables
- Replace Public/Private keys with fake value
> [DEVX-7140] Remove hardcoded keys

- Vonage.Common/Vonage.Common.csproj
- Vonage/Vonage.csproj
Reverts Vonage/vonage-dotnet-sdk#450
> release: revert "release: upgrade version to v6.8.0"

- Vonage.Common.Test/Vonage.Common.Test.csproj
- Vonage.Server.Test/Vonage.Server.Test.csproj
- Vonage.Test.Unit/Vonage.Test.Unit.csproj
All except xUnit due to breaking change
> refactor: package update

- .github/workflows/mutation-testing.yml
- README.md
- Vonage.Common/stryker-config.json
- Vonage.Server/stryker-config.json
- Vonage/stryker-config.json
Run mutation testing on all projects, with publish on dashboard
> ci: mutation testing improvement

- Vonage.Common.Test/Client/VonageHttpClientTest.cs
- Vonage.Common.Test/TestHelpers/FakeHttpMessageHandler.cs
- Vonage.Test.Unit/ConfigurationTest.cs
- Vonage/Configuration.cs
- Vonage/VonageClient.cs
https://github.com/Vonage/vonage-dotnet-sdk/issues/533
> feat: enable custom timeout on HttpClient

- Vonage/SubAccounts/SubAccountsClient.cs
Reduce duplication in SubAccountsClinet
> refactor: reduce duplication in SubAccountsClient

- Vonage/ProactiveConnect/Lists/UpdateList/UpdateListRequestBuilder.cs
Reduce duplication in ProactiveConnect UpdateList
> refactor: reduce duplication in ProactiveConnect UpdateList
