Nexmo.Api/NumberInsight.cs
While testing v2.3.1 against the quickstarts, I had an exception while deserialising 'roaming' property.
=> fixed 'roaming' property to match the json

Nexmo.Api.Test.Unit/Nexmo.Api.Test.Unit.csproj
According to the changelog, in the version 2.0.0-rc1 (2016-10-16), the configuration was moved from app.config to settings.json.
But, in the Api.Test.Unit project it's still there, causing build "not found file" error.
=> Removed unused App.config from project

Nexmo.Api/Request/VersionedApiRequest.cs
Bringing UserAgent in line with spec - also removing any parentheses from the framework description as the .NET Http library will object to them without spaces this will fix #145
=> Fixing malformed user agents

Nexmo.Api.Test.Unit/NumberTest.cs, Nexmo.Api.Test.Unit/VoiceStreamTest.cs, Nexmo.Api.Test.Unit/VoiceTalkTest.cs, Nexmo.Api/Voice/Call.Stream.cs, Nexmo.Api/Voice/Call.Talk.cs
allowing loop for talk and stream and making the serializer ignore if null and include if zero
=> Fixing default serialization of zero's in loop

Nexmo.Api.Test.Unit/VerifyTest.cs, Nexmo.Api/Nexmo.Api.csproj, Nexmo.Api/Nexmo.Api.nuspec, Nexmo.Api/Properties/AssemblyInfo.cs, Nexmo.Api/Verify/IVerifyClient.cs, Nexmo.Api/Verify/Psd2Request.cs, Nexmo.Api/Verify/VerifyClient.cs, Nexmo.Api/Verify/VerifyRequest.cs, Nexmo.Api/Verify/VerifyRequestBase.cs
Abstracted some of the overlap between regular verify and psd2 into a base class, added new psd2 functionality.
As I abstracted some of data struct into a base class I needed to move around some of the fields in the URL form for the regular Verify request's unit tests.
=> Adding Psd2 functionality

Nexmo.Api.Test.Unit/WebhookParserTests.cs, Nexmo.Api/Utility/WebhookParser.cs, README.md
ASP.NET / ASP.NET Core doesn't do the best job of handling the webhooks inbound from Vonage. This is mostly because we use `-` and `_` characters in our webhook structs. This update is adding a utility library to allow users to parse webhooks easily from the common endpoints they would be using. 
For reference the two main entry points I see are:
1. ASP.NET Core MVC/web API Controllers
2. ASP.NET Classic Web API Controllers
We support 3 content types for our webhooks as best I can gather
1. Queries - this is actually not technically a content type - but it's also the default state your account is put in when you create it. I've added the methods `ParseQuery` to handle the ASP.NET Core MVC `Request.Query` property inbound to the controller. I've also added `ParseQueryNameValuePairs` to …
=> Adding utility methods for parsing webhooks

Nexmo.Api.Test.Unit/WebhookStructsTest.cs, Nexmo.Api/Nexmo.Api.nuspec, Nexmo.Api/Voice/EventWebhooks/EventBase.cs
When the multi-input was added for ASR it looks like the parser was never added to the EventParser.
Adding the parse statement, and making sure that we have regression tests for this.
=> Fixing issue with ParseEvent for multiinput

Nexmo.Api.Test.Unit/MessagingTests.cs, Vonage.Test.Unit/MessagingTests.cs, Vonage/Messaging/DeliveryReceipt.cs
A missing `JsonIgnore` attribute causes an error when trying to deserialize Dlr struct when using a non-standard serializer - see #212. This PR resolves this issue for the Vonage data structure (the nexmo data structure was somehow fixed during the rebrand). Added tests for both nexmo/vonage.
=> Ignoring status for Vonage.Messaging.DeliveryReceipt.

Vonage.Test.Unit/MessagingTests.cs
Fixing a unit test that is breaking the build currently - when the new simplified version of `SendAnSms` is called, it adds the type to the request URL - which isn't accounted for in the unit test. As this is only a change to a test it will not warrant a new release.
=> fixing unit test

Vonage.Test.Unit/AccountTest.cs, Vonage.Test.Unit/ApplicationTests.cs, Vonage.Test.Unit/ConversionTest.cs, Vonage.Test.Unit/MessagingTests.cs, Vonage.Test.Unit/NumberInsightsTests.cs, Vonage.Test.Unit/NumbersTests.cs, Vonage.Test.Unit/PricingTests.cs, Vonage.Test.Unit/VerifyTest.cs, Vonage.Test.Unit/VoiceClientTests.cs, Vonage/Accounts/AccountClient.cs, Vonage/Applications/ApplicationClient.cs, Vonage/Conversions/ConversionClient.cs, Vonage/Messaging/SmsClient.cs, Vonage/NumberInsights/NumberInsightClient.cs, Vonage/Numbers/NumbersClient.cs, Vonage/Pricing/PricingClient.cs, Vonage/Redaction/RedactClient.cs, Vonage/Request/ApiRequest.cs, Vonage/ShortCodes/ShortCodesClient.cs, Vonage/Verify/VerifyClient.cs, Vonage/Voice/VoiceClient.cs
When the Async pattern was added to the .NET SDK we did so initially by adding a whole set of asynchronous methods and then pointing the synchronous methods at them. To preserve the call-stack when exceptions are raised we used the `GetAwaitor().GetResult()` pattern - unfortunately, that pattern exposes a potential deadlock condition when using single-threaded UI frameworks (e.g. Blazor Server). Consequentially I had to disentangle the Async and synchronous methods - and add new tests for the asynchronous methods to maintain coverage.
=> Syncronous methods blazor

.github/workflows/dotnet-core.yml, Nexmo.Api.Test.Unit/NccoTests.cs, Vonage.Test.Unit/NccoTests.cs, Vonage/LegacyNexmoLibrary/Voice/Nccos/RecordAction.cs, Vonage/Voice/Nccos/RecordAction.cs
`RecordAction` does not serialize correctly because the `Channels` parameter is not nullable, the default behavior is thus to serialize it to 0, which is not a valid setting. setting `Channels` parameter to nullable to have the serializer ignore it during serialization. Also adding tests to test a minimalist version of the `RecordAction`
=> setting Channels parameter to nullable

Vonage.Test.Unit/MessagingTests.cs, Vonage/Messaging/SendSmsRequest.cs
Adding `entity-id` and `content-id` for DLT
=> adding entity-id and content-id to sms request body

Vonage.Test.Unit/WebhookStructsTest.cs, Vonage/Voice/EventWebhooks/CallStatusEvent.cs, Vonage/Voice/EventWebhooks/DetailedStatus.cs
Adding `detail` field to Status event webhooks
=> adding detail to status-webhooks

.github/workflows/dotnet-core.yml, .github/workflows/publish-nuget.yml, README.md
Moving the GHA and readme to 5.x (codecov will need to catchup with the badge)
=> moving readme/GHA to 5.x

Vonage.Test.Unit/NumberInsightsTests.cs, Vonage/NumberInsights/AdvancedInsightsResponse.cs, Vonage/NumberInsights/StandardInsightResponse.cs, Vonage/NumberInsights/StringOrObjectConverter.cs
The Number Insights API changed their response for various fields to indicate when we are missing info versus the data is just unknown. This adds null support to:
* Current Carrier child values
* `reachable`
* `ported`
* `roaming`
It also adds support for `roaming` to return a string value, but be parsed into the old object format.
=> Support for NI Null values

Vonage/Logger/LogProvider.cs
VCC Incident on the 23rd of November 2021 we believe caused by this static function using a non thread safe Dictionary.
The incident in question.
https://vonage.slack.com/archives/CFZ9H9AKG/p1637659099179000
https://newvoicemedia.my.salesforce.com/a9t4G0000004FtYQAU
stack from logging during incident:
```
"StackTrace": " at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)\n at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)\n at Vonage.Logger.LogProvider.GetLogger(String category)\n at Vonage.PemParse.DecodePEMKey(String pemstr)\n at NewVoiceMedia.WebRtc.Nexmo.NexmoToken.CreateToken(Dictionary`2 payload, String region) in /home/src/WebRtc/Nexmo/NexmoToken.cs:line 29\n at …
```
=> Replace Dictionary with ConcurrentDictionary

.github/workflows/mutation-testing.yml, Vonage.sln
Creating a manual workflow in order to run mutation testing analysis on the solution. I decided to keep it manual because this analysis can be a bit slow, hence we can't include it in every build.
Note: I wasn't able to run it yet as the workflow doesn't exist on main. So it's a blind push for now, even though I'm confident.
=> Add mutation workflow

.github/workflows/mutation-testing.yml
I had to fix the workflow given Stryker was not compatible with .Net Core 3.1 🧟 
Here's the proof it works (ran from the branch): https://github.com/Vonage/vonage-dotnet-sdk/actions/runs/3182422444
The mutation report is available as workflow artifact.
=> Remove specific .net versioning for mutation pipeline

.github/workflows/dotnet-core.yml, Vonage.Test.Unit/Vonage.Test.Unit.csproj
Add SonarCloud analysis in the main pipeline
Remove unsupported client frameworks (.net core < 3.1)
Add .Net6 client framework given .NetCore3.1 will get out-of-support this month
=> Sonarcloud integration

Vonage.Test.Unit/Vonage.Test.Unit.csproj, Vonage/Vonage.csproj
Upgrade SDK to netstandard2.0, Upgrade TestProject to everything above 4.6.2, and update all libraries.
NetStandard2.0 represents a unified version of the framework that covers all supported versions. Switching to a "netstandard2.0" target version makes it easier for us in dependency management and guarantees we're aligned with support. Also, version 4.5.2 is out-of-support since April 2022.
=> DEVX-6785 Framework update

Vonage.Video.Beta.Test/Common/MaybeTest.cs, Vonage.Video.Beta.Test/Common/ResultTest.cs, Vonage.Video.Beta/Common/Maybe.cs, Vonage.Video.Beta/Common/Result.cs, Vonage.Video.Beta/Common/UnsafeValueException.cs
Add "unsafe" methods to retrieve a monad value, throwing an exception if the monad is not in the expected state.
This is a provided workaround for people preferring exceptions instead of using transformation mechanisms (Match, Map, Bind)
=> Add unsafe methods on Maybe & Result

Vonage.Video.Beta.Test/Common/Monads/ResultTest.cs, Vonage.Video.Beta.Test/Video/Archives/AddStream/AddStreamTest.cs, Vonage.Video.Beta.Test/Video/Archives/CreateArchive/CreateArchiveTest.cs, Vonage.Video.Beta.Test/Video/Archives/RemoveStream/RemoveStreamTest.cs, Vonage.Video.Beta.Test/Video/Moderation/MuteStreams/MuteStreamsTest.cs, Vonage.Video.Beta.Test/Video/Sessions/ChangeStreamLayout/ChangeStreamLayoutTest.cs, Vonage.Video.Beta.Test/Video/Sessions/CreateSession/CreateSessionDeserializationTest.cs, Vonage.Video.Beta.Test/Video/Signaling/SendSignal/SendSignalTest.cs, Vonage.Video.Beta.Test/Video/Signaling/SendSignals/SendSignalsTest.cs, Vonage.Video.Beta/Common/Monads/Result.cs, Vonage.Video.Beta/Common/Monads/ResultExtensions.cs, Vonage.Video.Beta/Video/VideoHttpClient.cs
Implement chainable extension methods for MapAsync and BindAsync on Task<Result<T>>
Implement IfFailure on Result<T> to extract the success more easily
=> MapAsync / BindAsync extension methods

Vonage/Vonage.csproj
Upgrading version to 6.0.4
The version on the SDK was still 6.0.2-rc while the released version is 6.0.3
=> Update version to 6.0.4

Vonage.Test.Unit/MessagingTests.cs, Vonage/Messaging/SendSmsRequest.cs, Vonage/Messaging/SmsType.cs
These enum values weren't used in any test. Therefore, no further change is required
=> [DEVX-6796] Remove deprecated message types (wappush, val, vcar)

Vonage.Test.Unit/NumbersTests.cs, Vonage/Numbers/INumbersClient.cs, Vonage/Numbers/NumbersClient.cs, Vonage/Request/ApiRequest.cs
Move ApiKey/ApiSecret in the query string for NumbersAPI instead of the body.
The weird part is that the body is a computed query string that always includes credentials. This method is used by several endpoints and is painful to change. The method is not tested individually (only through E2E tests) with a high complexity index.
I implemented an easy workaround: an additional optional parameter to exclude credentials from the query string. This is clearly a short-term solution, given my long-term goal is to decommission this unmaintainable ApiRequest anyway.
Other tasks included in this PR:
- Refactor Number Tests to make them easier to understand and maintain (especially remove the branching in tests)
- Add missing Xml Documentations on NumbersClient
- Automatic …
=> [DEVX-7128] NumbersAPI update

Vonage.Common.Test/Extensions/FsCheckExtensions.cs, Vonage.Common.Test/UseCaseHelper.cs
Fix for issue https://github.com/Vonage/vonage-dotnet-sdk/issues/396
=> fix: exclude '{' and '}' from non-empty strings in PBT

Vonage/Jwt.cs, Vonage/Voice/ITokenGenerator.cs
This PR addresses the issue https://github.com/Vonage/vonage-dotnet-sdk/issues/287 by adding an optional parameter to add custom claims to token generation.
=> feat: add optional claims when generating a token

Vonage/Accounts/AccountClient.cs
`apiKey` is an optional parameter used in the path. It leads to a 404 if not provided.
The fix uses the `apiKey` from Credentials if not provided.
=> fix: SubAccounts implementation

Vonage.Test.Unit/Data/NccoTests/TestConversation-request.json, Vonage/Voice/Nccos/ConversationAction.cs
The default value is supposed to be `true`, but the default serializer options ignore default values. As the default for bool is `false`, the value is never provided.
The main problem is even more significant: `true` is never the default value on the object itself...
Changing the default serialization options would generate too many side effects. 
I set the following on the `StartOnEnter`property instead:
```csharp
DefaultValueHandling = DefaultValueHandling.Include
```
https://github.com/Vonage/vonage-dotnet-sdk/issues/463
=> fix: conversation StartOnEnter

.github/workflows/net-build.yml
Increase java version to 17, as the current version is outdated.
This is required for the SonarSource analysis
https://github.com/Vonage/vonage-dotnet-sdk/issues/480
=> ci: increase java version to 17

Vonage.Server.Test/TestHelpers/E2EHelper.cs, Vonage/Vonage.csproj
Use factory method to create Configuration instead.
This was causing an issue when building a Signed version
=> refactor: remove InternalsVisibleTo property

.github/workflows/publish-nuget-v2.yml, .github/workflows/release.yml, Vonage.sln
- Improve release time
- No dependency towards Nexmo GitHub Action
- No tag creation given it's already created via GitHub Release
=> ci: release pipeline

Vonage.Test/Data/Webhooks/ShouldDeserializedAnswered_GivenStartTimeIsNull.json, Vonage.Test/Vonage.Test.csproj, Vonage.Test/WebhookStructsTest.cs, Vonage/Voice/EventWebhooks/Answered.cs
Fix for issue https://github.com/Vonage/vonage-dotnet-sdk/issues/567
The start time value can be null, but the related property isn't
=> fix: [breaking] make StartTime nullable on Answered webhook

Vonage/PemParse.cs
Fixes edge case Exception importing private key when `D` is shorter in length than `MODULUS` by 8 bits or more.
If `D` is shorter, it is copied to the end of a new array with the same length as `MODULUS`. Naive, but this is a rare edge case.
This fixes issue #357 that I just ran into using an older Vonage application private key.
Ran unit tests with old and new keys and published to our production server (which uses multiple private keys).
=> Fix edge case importing RSA key
